### ISSUE TITLE
meta: Rename markdown files to have .md extension

### ISSUE THREAD

**Issue by Insti** [exercism/request-new-language-track#25]
Todo: 

- [x] Identify files with markdown content. 
  - `CHECKLIST`
  - `CONSISTENCY`
  - `TRAVIS`
- [ ] Rename the markdown files in this repository to have `.md` extentsion.
- [ ] Update `bin/bootstrap`, which relies on those filenames.

Ref: https://github.com/exercism/request-new-language-track/pull/23#issuecomment-302954918
